CREATE OR REPLACE DATABASE SNOWPARK_DB


---------------------------------------
USE DATABASE SNOWPARK_DB

CREATE OR REPLACE SCHEMA STAGGING;
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA TRANSFORMED;
CREATE OR REPLACE SCHEMA CURATED;

---------------------------------------
USE SCHEMA SNOWPARK_DB.STAGGING;

CREATE OR REPLACE TABLE SNOWPARK_DB.STAGGING.INDIA_SALES_ORDER_CP
(
ORDER_ID VARCHAR(1000),
CUSTOMER_NAME VARCHAR(1000),
MOBILE_MODEL VARCHAR(1000),
QUANTITY VARCHAR(1000),
PRICE_PER_UNIT VARCHAR(1000),
TOTAL_PRICE VARCHAR(1000),
PROMOTION_CODE VARCHAR(1000),
ORDER_AMOUNT VARCHAR(1000),
GST VARCHAR(1000),
ORDER_DATE VARCHAR(1000),
PAYMENT_STATUS VARCHAR(1000),
SHIPPING_STATUS VARCHAR(1000),
PAYMENT_METHOD VARCHAR(1000),
PAYMENT_PROVIDER VARCHAR(1000),
MOBILE VARCHAR(1000),
DELIVERY_ADDRESS VARCHAR(1000)
);

---------------------------------------USA
CREATE OR REPLACE TABLE SNOWPARK_DB.STAGGING.USA_SALES_ORDER_CP
(
SOURCE_DATA VARIANT
);
---------------------------------------FRANCE
CREATE OR REPLACE TABLE SNOWPARK_DB.STAGGING.FRANCE_SALES_ORDER_CP
(
SOURCE_DATA VARIANT
);

---------------------------------------Storage integration
CREATE STORAGE INTEGRATION SNOWPARK_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::157005383404:role/snowflakesnowparkrole'
STORAGE_ALLOWED_LOCATIONS = ('s3://snowpark-data-bucket/');
---------------------------------------check connection
DESC INTEGRATION SNOWPARK_INT

---------------------------------------create external stage

CREATE STAGE SNOWPARK_DB.STAGGING.SNOWPARK_STAGE
STORAGE_INTEGRATION = SNOWPARK_INT
URL = 's3://snowpark-data-bucket/';

---------------------------------------should see the data in S3
ls @SNOWPARK_DB.STAGGING.SNOWPARK_STAGE;




