select *
from DBT_HOL_2025_PROD.PUBLIC_03_MARTS.FCT_PNL_BY_DESK

---------Cumulative PnL by Desk and Ticker
SELECT DESK, TICKER, SUM(CUMULATIVE_PNL_USD) AS TOTAL_PNL
FROM DBT_HOL_2025_PROD.PUBLIC_03_MARTS.FCT_PNL_BY_DESK
GROUP BY DESK, TICKER
ORDER BY TOTAL_PNL DESC;


---------Daily Total Profit and Lost Trend
SELECT TRADE_DATE, SUM(TOTAL_PNL_USD) AS DAILY_PNL
FROM DBT_HOL_2025_PROD.PUBLIC_03_MARTS.FCT_PNL_BY_DESK
GROUP BY TRADE_DATE
ORDER BY TRADE_DATE;



---------Performance Comparison: Actual vs. Market
SELECT TRADE_DATE, 
       AVG(AVG_PNL_USD) AS AVG_PNL,
       AVG(AVG_MARKET_PERFORMANCE_PCT) AS MARKET_PCT,
       AVG(AVG_RELATIVE_PERFORMANCE_PCT) AS RELATIVE_PCT
FROM DBT_HOL_2025_PROD.PUBLIC_03_MARTS.FCT_PNL_BY_DESK
GROUP BY TRADE_DATE
ORDER BY TRADE_DATE;


---------Trade Distribution by Region

SELECT REGION, COUNT(*) AS TOTAL_TRADES
FROM DBT_HOL_2025_PROD.PUBLIC_03_MARTS.FCT_PNL_BY_DESK
GROUP BY REGION;

---------Best vs Worst Price Execution Count

SELECT TICKER, SUM(BEST_PRICE_TRADES) AS BEST, SUM(WORST_PRICE_TRADES) AS WORST
FROM DBT_HOL_2025_PROD.PUBLIC_03_MARTS.FCT_PNL_BY_DESK
GROUP BY TICKER
ORDER BY BEST DESC;