CREATE OR REPLACE DATABASE TIMETRAVEL_DB;

CREATE OR REPLACE SCHEMA TIMETRAVEL_DB.TIMETRAVEL_DATA;


------------------Create EMPLOYEE Table
CREATE OR REPLACE TABLE TIMETRAVEL_DB.TIMETRAVEL_DATA.EMPLOYEE (
    EMPLOYEE_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    DEPARTMENT STRING,
    SALARY FLOAT,
    HIRE_DATE DATE
);

------------------Populate the EMPLOYEE Table
INSERT INTO TIMETRAVEL_DB.TIMETRAVEL_DATA.EMPLOYEE VALUES 
('E1', 'John', 'Doe', 'Finance', 75000.50, '2020-01-15'), 
('E2', 'Jane', 'Smith', 'HR', 68000.00, '2018-03-20'), 
('E3', 'Alice', 'Johnson', 'IT', 92000.75, '2019-07-10'),
('E4', 'Bob', 'Williams', 'Sales', 58000.25, '2021-06-01'), 
('E5', 'Charlie', 'Brown', 'Marketing', 72000.00, '2022-04-22'), 
('E6', 'Emily', 'Davis', 'IT', 89000.10, '2017-11-12'), 
('E7', 'Frank', 'Miller', 'Finance', 83000.30, '2016-09-05'), 
('E8', 'Grace', 'Taylor', 'Sales', 61000.45, '2023-02-11'),
('E9', 'Hannah', 'Moore', 'HR', 67000.80, '2020-05-18'), 
('E10', 'Jack', 'White', 'Marketing', 70000.90, '2019-12-25');

--
SELECT * FROM TIMETRAVEL_DB.TIMETRAVEL_DATA.EMPLOYEE;

------------------Simulate Data Deletion
DELETE FROM TIMETRAVEL_DB.TIMETRAVEL_DATA.EMPLOYEE
WHERE EMPLOYEE_ID IN ('E2', 'E7');

--
SELECT * FROM TIMETRAVEL_DB.TIMETRAVEL_DATA.EMPLOYEE;


------------------Get the QUERY_ID of the DELETE
SELECT *
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_USER())
WHERE QUERY_TEXT ILIKE 'DELETE%'
ORDER BY START_TIME DESC
LIMIT 1;

------------------Use Time Travel to View Deleted Data
-- Replace 'your_query_id_here' with your real query ID
SELECT * 
FROM TIMETRAVEL_DB.TIMETRAVEL_DATA.EMPLOYEE 
BEFORE (STATEMENT => '01bbd3cd-020d-1b09-000d-306b000d2426');



------------------Restore Deleted Records
INSERT INTO TIMETRAVEL_DB.TIMETRAVEL_DATA.EMPLOYEE
SELECT *
FROM TIMETRAVEL_DB.TIMETRAVEL_DATA.EMPLOYEE 
BEFORE (STATEMENT => '01bbd3cd-020d-1b09-000d-306b000d2426')
WHERE EMPLOYEE_ID IN ('E2', 'E7');


 ------------------Confirm Recovery
SELECT * FROM TIMETRAVEL_DB.TIMETRAVEL_DATA.EMPLOYEE
ORDER BY EMPLOYEE_ID;


